# Legacy workflow - Use deploy-fullstack.yml instead
# This workflow is kept for reference but should not be used

name: Legacy - Build and deploy Node.js app to Azure Web App - Collab

on:
  workflow_dispatch:
  # Removed automatic trigger - use deploy-fullstack.yml instead

jobs:
  build:
    runs-on: ubuntu-latest
    if: false  # Disabled - use deploy-fullstack.yml instead
    
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies for all projects
        run: |
          npm install
          cd frontend && npm install
          cd ../backend && npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Copy frontend build to backend public folder
        run: |
          mkdir -p backend/public
          cp -r frontend/build/* backend/public/

      - name: Test backend
        run: |
          cd backend
          npm run test --if-present

      - name: Zip backend with frontend for deployment
        run: |
          cd backend
          zip -r ../release.zip . -x "node_modules/*" "*.log"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_082CE0ACB88148CAB2EEA75FA40B5C25 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_78A8038E871C4FDEAB89BE437679D6DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_76E14732AEB64CEA975F947A3019625D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Collab'
          slot-name: 'Production'
          package: .
=======
      - name: Workflow disabled
        run: |
          echo "This workflow has been disabled."
          echo "Please use the deploy-fullstack.yml workflow instead."
          echo "This file is kept for reference only."
          exit 1
>>>>>>> 70d45d17be070077ddd65a950927a3d2d49058b9
          